<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

<meta http-equiv="X-UA-Compatible" charset=utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title> ECMall </title>
<link href="<?php echo $this -> RootUrl(); ?>/adminres/css/admin.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="<?php echo $this -> RootUrl(); ?>/js/ckeditor/ckeditor.js"></script>
<script type="text/javascript" src="<?php echo $this -> RootUrl(); ?>/js/jquery.js"></script>
<script type="text/javascript">
	var ofck;
	window.onload=function (){
		ofck = CKEDITOR.replace("content");	
	}
</script>
<script language="javascript" type="text/javascript" src="<?php echo $this->RootUrl()?>/js/date/WdatePicker.js"></script>
<style type="text/css">
<!--
body {background: #fcfdff}
-->
</style>
</head>
<body><div id="rightTop">
  <p>邮件</p>
  <ul class="subnav">
    <li><a class="btn1" href="<?php echo $this->RootUrl()?>/admin/email/index">管理</a></li>
    <li><span>添加邮件</span></li>
  </ul>
</div>
<div class="info">
<div id="iframe_left" style="width:80%">
  <form method="post" enctype="multipart/form-data" id="test_form" action="<?php echo $this->RootUrl();?>/admin/email/send-form">
    <table class="infoTable">
      <tr>
          <th></th>
        <td class="paddingT15"><h3>邮件信息</h3></td>
      </tr>
       <tr>
        <th class="paddingT15"> 收件人:</th>
        <td><input name="to" type="text" size="70" id="to" /></td>
      </tr>
      <tr>
        <th class="paddingT15"> 邮件标题:</th>
        <td><input name="title" type="text" size="80" /></td>
      </tr>
       <tr>
        <th class="paddingT15"> 邮件内容:</th>
        <td class="paddingT15 wordSpacing5"><textarea id="content" name="content"></textarea></td>
      </tr>
      <tr>
        <th></th>
        <td class="ptb20"><input class="formbtn" type="submit" name="submit" value="提交" />&nbsp;&nbsp;&nbsp;&nbsp;
          <input class="formbtn" type="reset" name="Reset" value="重置" /></td>
      </tr>
    </table>
  </form>
  </div>
  <div id="iframe_right" style="width:18%">
	<iframe src="<?php echo $this->RootUrl()?>/admin/member/send"  height="400" frameborder="0" style="width:100%"></iframe>	
  </div>
</div>

<p id="page_footer">Copyright 2003-2009 ShopEx Inc.,All rights reserved.</p>
</body>
</html>