<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7 charset=utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title> ECMall </title>
<link href="<?php echo $this -> RootUrl(); ?>/adminres/css/admin.css" rel="stylesheet" type="text/css" />
<style>
	#dq select{
		width:100px;
		margin-left:20px;
	}
  </style>
  <script src="<?php echo $this -> RootUrl(); ?>/adminres/js/jquery-1[1].2.6.js" type="text/javascript"></script>
<script type="text/javascript" src="<?php echo $this -> RootUrl(); ?>/js/jquery.js" charset="utf-8"></script>
<script type="text/javascript" src="<?php echo $this -> RootUrl(); ?>/adminres/js/ecmall.js" charset="utf-8"></script>
<script type="text/javascript" src="<?php echo $this -> RootUrl(); ?>/adminres/js/admin.js" charset="utf-8"></script>
  <script src="<?php echo $this -> RootUrl(); ?>/adminres/js/jquery.provincesCity.js" type="text/javascript"></script>
  <script src="<?php echo $this -> RootUrl(); ?>/adminres/js/provincesdata.js" type="text/javascript"></script>
  <script>
	//调用插件
	$(function(){
		$("#dq").ProvinceCity();
	});
  </script>
<style type="text/css">
<!--
body {background: #fcfdff}
-->
</style>
</head>
<body><div id="rightTop">
  <ul class="subnav">
        <li><span>管理</span></li>
        <li><a class="btn1" href="<?php echo $this->RootUrl();?>/admin/order/index">订单列表</a></li>
      </ul>
</div>
<div class="tdare">
  <table width="100%" cellspacing="0" class="dataTable">
    <tr class="tatr2">
      <td width="20" class="firstCell">订单号:<input type="text" name="order" /></td>
    </tr>
    <tr class="tatr2">
      <td class="firstCell"><div id="dq">地区:</div></td>
    </tr>
    <tr class="tatr2">
      <td class="firstCell">配送方式
      <select>
	<option>-请选择-</option>
      </select>
      </td>
    </tr>
    <tr class="tatr2">
      <td class="firstCell">支付方式
      <select>
	<option>-请选择-</option>
      </select>
      </td>
    </tr>
      <tr class="tatr2">
      <td class="firstCell"><center><input type="submit" name="submit" class="formbtn" value="查询"/>&nbsp;&nbsp;&nbsp;<input type="reset" name="reset" class="formbtn" value="重置"/></center></td>
    </tr>
      </table>
  <div class="clear"></div>  
</div>
<p id="page_footer">&copy;.&copy;。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。&copy;.&copy;</p>
</body>
</html>