<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7 charset=utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title> ECMall </title>
<link href="<?php echo $this -> RootUrl(); ?>/adminres/css/admin.css" rel="stylesheet" type="text/css" />
<script type="text/javascript">
//<!CDATA[
var SITE_URL = "http://localhost/ecmall";
//]]>
</script>
<script type="text/javascript" src="js/jquery.js" charset="utf-8"></script>
<script type="text/javascript" src="js/ecmall.js" charset="utf-8"></script>
<script type="text/javascript" src="js/admin.js" charset="utf-8"></script>
<style type="text/css">
<!--
body {background: #fcfdff}
-->
</style>
</head>
<body><div id="rightTop">
  <p>商品</p>
  <ul class="subnav">
    <li><a class="btn1" href="<?php echo $this->RootUrl()?>/admin/goods/index">管理</a></li>
    <li><span>添加商品</span></li>
  </ul>
</div>
<div class="info">
  <form method="post" enctype="multipart/form-data" id="test_form" action="<?php echo $this->RootUrl();?>/admin/goods/add-form">
    <table class="infoTable">
      <tr>
          <th></th>
        <td class="paddingT15">请输入商品信息</td>
      </tr>
      <tr>
        <th class="paddingT15"> 商品名称:</th>
        <td class="paddingT15 wordSpacing5"><input class="infoTableInput2" name="user_name" type="text" id="user_name" /></td>
      </tr>
      <tr>
        <th class="paddingT15"> 商品分类:</th>
        <td class="paddingT15 wordSpacing5">
		<select name="class">
			<option value="0">请选择 ...</option>

		</select>
	</td>
      </tr>
      <tr>
        <th class="paddingT15"> 商品品牌:</th>
        <td class="paddingT15 wordSpacing5">
		<select name="brand">
			<option value="0">请选择 ...</option>

		</select>
	</td>
      </tr>
       <tr>
        <th class="paddingT15"> 商品售价:</th>
        <td><input name="price" type="text" size="10"/></td>
      </tr>
       <tr>
        <th class="paddingT15"> 商品图片:</th>
        <td class="paddingT15 wordSpacing5"><input name="phone" type="file" /></td>
      </tr>
      <tr>
        <th></th>
        <td class="ptb20"><input class="formbtn" type="reset" name="Reset" value="重置" />&nbsp;&nbsp;&nbsp;&nbsp;<input class="formbtn" type="submit" name="submit" value="提交" />
          </td>
      </tr>
    </table>
  </form>
</div>
<p id="page_footer">Copyright 2003-2009 ShopEx Inc.,All rights reserved.</p>
</body>
</html>