<?php header("content-type:text/html;charset=utf-8")?>
<script type="text/javascript" src="<?php echo $this -> rootUrl(); ?>/js/jquery.js" charset="utf-8"></script>
<script type='text/javascript'>
//图片插入编辑器
var img = '<img src="<?php echo $this -> rootUrl() . $this -> src;?>" />';
parent.ofck.insertHtml(img);
//图片添加至表单
var inputstr = '<input type="hidden" name="attach[<?php echo $this -> id;?>]" value="<?php echo $this -> path;?>" />';
$("#description_attach", parent.document).append(inputstr);
//form还原
$("#addform", parent.document).attr('target', '_self');
$("#addform", parent.document).attr('action', '<?php echo $this -> url( array( "action" => "insert") );?>' );

</script>