<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7 charset=utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title> ECMall </title>
<link href="<?php echo $this -> RootUrl(); ?>/adminres/css/admin.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="<?php echo $this -> RootUrl(); ?>/js/jquery.js" charset="utf-8"></script>
<script type="text/javascript" src="<?php echo $this -> RootUrl(); ?>/adminres/js/ecmall.js" charset="utf-8"></script>
<script type="text/javascript" src="<?php echo $this -> RootUrl(); ?>/adminres/js/admin.js" charset="utf-8"></script>
<script type="text/javascript">
chkChange = function(obj){
	checkobj = document.getElementsByName('check[]');
	len = checkobj.length;
	if(obj.checked == true){
		for(i=0;i<len;i++){
	        checkobj[i].checked = true;
		}
	}else{
		for(i=0;i<len;i++){
	        checkobj[i].checked = false;
		}
	}
}
</script>
<style type="text/css">
<!--
body {background: #fcfdff}
-->
</style>
</head>
<body>
<div id="rightTop">
  <p>商品属性管理</p>
  <ul class="subnav">
        <li><span></span></li>
        <li><a class="btn1" href="<?php echo $this->url(array('action'=>'add'));?>">新增属性</a></li>
 </ul>
</div>
<div class="mrightTop">
  <div class="fontl">
   
  </div>
  <div class="fontr"> </div>
</div>
<div class="tdare">
  <form name='propertylist' action="<?php echo $this -> url(array('action'=>'delete','page'=>''));?>" method="post">
  <table width="100%" cellspacing="0" class="dataTable">
      <tr class="tatr1">
          <td style="width:8%" class="firstCell"><input name="selectall" type="checkbox" onclick="chkChange(this)" />全选</td>
          <td style="width:20%">属性名称</td>
          <td style="width:46%">类型名称</td>
          <td style="width:8%" class="handler">操作</td>
     </tr>
	<?php foreach($this->propertyList as $property){ ?>
     <tr class="tatr2">
      <td class="firstCell"><input name="check[]" value="<?php echo $property -> id; ?>" type="checkbox" />&nbsp;<?php echo $property -> id; ?></td>
      <td><?php echo $property -> name; ?></td>
      <td><?php echo $property -> type_name;?></td>
      <td style="text-align:center;">
        <a href="<?php echo $this -> url(array('action' => 'edit', 'propertyId' => $property -> id));?>">编辑</a> | 
        <a href="javascript:drop_confirm('您确定要删除该商品属性？',
        '<?php echo $this -> url(array('action' => 'delete', 'propertyId' => $property -> id));?>')">删除</a> 
      </td>
    </tr>
    <?php } ?>
    <tr class="tar2"><td style="text-align: center;"><input type="submit" value="删除所选" /></td><td colspan="5" style="text-align: center;"><?php include APPLICATION_PATH . '/admin/views/scripts/common/page.phtml';?></td></tr>
   </table>
   </form>
  <div class="clear"></div>  
</div>
<p id="page_footer">&copy;.&copy;。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。&copy;.&copy;</p>
</body>
</html>