<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7 charset=utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title> ECMall </title>
<link href="<?php echo $this -> RootUrl(); ?>/adminres/css/admin.css" rel="stylesheet" type="text/css" />
<script type="text/javascript">
	function checkall(){
		if(document.form.check.checked){
			var check = document.getElementsByName('checked[]');
			for(var i=0;i<check.length;i++){
				
				check[i].checked = true;
			}
		}else{
			var check = document.getElementsByName('checked[]');
			for(var i=0;i<check.length;i++){
				
				check[i].checked = false;
			}
		}
	}
</script>
<script type="text/javascript" src="<?php echo $this -> RootUrl(); ?>/js/jquery.js" charset="utf-8"></script>
<script type="text/javascript" src="<?php echo $this -> RootUrl(); ?>/adminres/js/ecmall.js" charset="utf-8"></script>
<script type="text/javascript" src="<?php echo $this -> RootUrl(); ?>/adminres/js/admin.js" charset="utf-8"></script>
<style type="text/css">
<!--
body {background: #fcfdff}
-->
</style>
</head>
<body>
<div class="mrightTop">
  <div class="fontl">
       <div class="left" style="font-size:16px;color:#999;">
          <p>商品咨询列表</p>
      </div>
  </div>
  <div class="fontr"> </div>
</div>
<div class="tdare">
<form action="<?php echo $this -> RootUrl(); ?>/admin/consult/delete" method="post" name="form" >
  <table width="100%" cellspacing="0" class="dataTable">
        <tr class="tatr1">
      <td width="20" class="firstCell"><input type="checkbox" name="check" onclick='checkall(this)'/></td>
      <td>商品名称</td>
      <td><span ectype="order_by" fieldname="store_name">会员名称</span></td>
      <td><span ectype="order_by" fieldname="sgrade">咨询问题</span></td>
      <td class="table-center"><span ectype="order_by" fieldname="add_time">状态</span></td>
      <td class="table-center"><span ectype="order_by" fieldname="state">提问时间</span></td>
	<td class="handler">操作</td>
    </tr>
	<?php foreach($this->dataList as $data){ ?>
            <tr class="tatr2">
      <td class="firstCell"><input type="checkbox" name="checked[]" value="<?php echo $data['id'] ;?>"/></td>
      <td><?php echo $data['goods_name']; ?></td>
      <td>
      <?php echo $data['user_name']; ?>
      </td>
      <td><?php echo $data['question']; ?></td>
      <td class="table-center"><?php if($this->data['reply_status'] === 0){echo "未回复";}else{echo "已回复";} ?></td>
      <td class="table-center"><?php echo date("Y-m-d H:i:s",$data['ask_time']); ?></td>
            <td class="handler">
                <a href="<?php echo $this -> RootUrl(); ?>/admin/consult/show/id/<?php echo $data['id']; ?>">查看</a> | <a href="javascript:drop_confirm('您确定要删除该商品咨询？', '<?php echo $this -> RootUrl(); ?>/admin/consult/delete/id/<?php echo $data['id']; ?>');">删除</a> 
        </td>
    </tr>
    <?php } 
    ?>
    
    <tr class="tar2"><td style="text-align: center;"><input type="submit" value="删除所选" /></td><td colspan="5" style="text-align: center;"><?php include APPLICATION_PATH . '/admin/views/scripts/common/page.phtml';?></td></tr>
      </table>
      </form>
  <div class="clear"></div>  
</div>
<p id="page_footer">&copy;.&copy;。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。&copy;.&copy;</p>
</body>
</html>