<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7 charset=utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title> ECMall </title>
<link href="<?php echo $this -> RootUrl(); ?>/adminres/css/admin.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="<?php echo $this -> RootUrl(); ?>/js/jquery.js" charset="utf-8"></script>
<script type="text/javascript" src="<?php echo $this -> RootUrl(); ?>/adminres/js/ecmall.js" charset="utf-8"></script>
<script type="text/javascript" src="<?php echo $this -> RootUrl(); ?>/adminres/js/admin.js" charset="utf-8"></script>
<style type="text/css">
<!--
body {background: #fcfdff}
-->
</style>
</head>
<body>
<div id="rightTop">
  <p>商品类型管理</p>
  <ul class="subnav">
        <li><span></span></li>
        <li><a class="btn1" href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'goodstype', 'action' => 'add'),null, true, true);?>">新增类型</a></li>
 </ul>
</div>
<div class="mrightTop">
  <div class="fontl">
    
  </div>
  <div class="fontr"> </div>
</div>
<div class="tdare">
  <table width="100%" cellspacing="0" class="dataTable">
      <tr class="tatr1">
          <td style="width:8%" class="firstCell">类型ID</td>
          <td style="width:40%">商品类型名称</td>
          <td style="width:30%" class="handler">操作</td>
     </tr>
	<?php foreach($this->goodsType as $type){ ?>
     <tr class="tatr2">
      <td class="firstCell"><?php echo $type -> id; ?></td>
      <td><?php echo $this -> escape($type -> type_name); ?></td>
      <td style="text-align:center;">
        <a href="<?php echo $this -> url(array('module' => 'admin', 'controller' => 'goodstype', 'action' => 'edit', 'id' => $type -> id),null, true, true);?>">编辑</a> | 
        <a href="javascript:drop_confirm('您确定要删除该商品类型？', '<?php echo $this -> url(array('module' => 'admin', 'controller' => 'goodstype', 'action' => 'delete', 'id' => $type -> id),null, true, true);?>')">删除</a> |  
        <a href ="<?php echo $this -> url(array('module' => 'admin', 'controller' => 'goodstypeproperty', 'action' => 'index', 'typeId' => $type -> id),null, true, true);?>">属性列表</a>
      </td>
    </tr>
    <?php } ?>
    <tr class="tar2"><td colspan="3" style="text-align: center;"><?php include APPLICATION_PATH . '/admin/views/scripts/common/page.phtml';?></td></tr>
   </table>
  <div class="clear"></div>  
</div>
<p id="page_footer">&copy;.&copy;。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。&copy;.&copy;</p>
</body>
</html>