<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link href="<?php echo $this -> RootUrl(); ?>/css/indexcss.css" rel="stylesheet" type="text/css">
<title>首页</title>
</head>

<body>
		<!--顶部开始-->
    	<div class="topmx">
        	<div class="logintop">您好，欢迎来到源码商城！&nbsp;&nbsp;&nbsp;&nbsp;[<a href="#">请登录</a>][<a href="#">免费注册</a>]</div>
        	<a href="#" class="logintop3">帮助</a>
            <a href="#" class="logintop1">交易安全</a>
            <a href="#" class="logintop2">购物车</a>
        </div>
        <div style="clear:both;"></div> 
        <!--顶部结束-->
 	<!--外边框开始-->
	<div id="shop">
    	<!--头部分开始-->
    	<div class="top">
               <div class="logo">
                    <div class="logo1">
                        <img src="image/logo1.gif" />
                    </div>
                    <div class="logo2">
                        <img src="image/logo2.gif" />
                    </div>
                    
               </div>   
              
               <div class="help">
                   <input type="text" class="text" />
                   <select class="chancebox">
                   		<option>所有分类</option>
                   		<option>test</option>
                   </select>
                   <a href="#"><img class="submit" src="image/indexsubmit.gif"></a>
               </div>
      	</div>
        <div style="clear:both;"></div> 
        <!--头部分结束-->
        <!--导航栏开始-->
        <div class="navigation">
        	<a href="#"><div class="N1">首页</div></a>
        	<a href="#"><div class="N2">商品中心</div></a>
            <a href="#"><div class="N2">新闻中心</div></a>
            <a href="#"><div class="N2">商城活动</div></a>
            <a href="#"><div class="N2">品牌列表</div></a>
            <a href="#"><div class="N2">帮助中心</div></a>
            <a href="#"><div class="N2">发货通知</div></a>
            <a href="#"><div class="N2">在线留言</div></a>
            <div class="N3">您的购物车里有0件商品</div>
            <div class="N4"><a class="F4" href="#">去结算</a></div>
        </div>
        <div style="clear:both;"></div> 
        <!--导航栏结束-->
        <!--中间部分开始-->
        <div class="center">
        	<!--中间部分第一块开始-->
          <div class="L1"></div>
            <div class="L2">
                    <a href="#"><img class="N5" src="image/a.gif"/></a>
                    <a href="#"><img class="N6" src="image/b.gif"/></a>
                    <a href="#"><img class="N7" src="image/c.gif"/></a>
            </div>
            
            <div class="L3">
              
                  <div class="L3_2">
                            <div class="L3_1">商城活动</div>
                            <div class="L3_3">more&nbsp;>></div>
                  </div>
                  <ul type="disc" class="L3_4">
                  		<li>帅气感短外套，时髦OL十月扮靓必备</li>
                        <li>凉意深秋衣橱必备时尚单品百穿不腻</li>
                        <li>超人气百搭外套张扬秋日时尚新活力</li>
                        <li>各式俏皮薄款外套，20℃天气正流行</li>
                        <li>2010年入秋优雅毛衣新时尚购买方向</li>
                        <li>俏MM巧选外套，五种风格深秋人气旺</li>
                        <li>温暖高领衫，降温天气天天必备单品</li>	
                  </ul>
           	</div>
            <div class="L4"><img src="image/L4.gif" /></div>
            <div class="L5"><img src="image/L5.gif" /></div>
            <!--中间部分第一块结束-->
             <div style="clear:both;"></div> 
            <!--中间部分第二块产品分类开始-->
            <div class="L6">
            		<div class="L6_1"><div class="L6_2">产品分类</div></div>
                    <div class="L6_3">女装</div>
                         <dl class="L6_4">
                                <dd>春秋上装</dd>
                                <dd>夏季上装</dd>
                                <dd>外套风衣</dd>
                                <dd>内搭打底</dd>
                                <dd>连衣裙</dd>
                                <dd>半身裙</dd>
                                <dd>舒适长裤</dd>
                                <dd>经典裤子</dd>
                                <dd>鞋子</dd>
                        </dl>  
                         <div class="L6_3">男装</div>
                         <dl class="L6_4">
                                <dd>春秋上装</dd>
                                <dd>夏季上装</dd>
                                <dd>外套风衣</dd>
                                <dd>内搭打底</dd>
                                <dd>连衣裙</dd>
                                <dd>半身裙</dd>
                                <dd>舒适长裤</dd>
                                <dd>经典裤子</dd>
                                <dd>鞋子</dd>
                        </dl>  
                        <div class="L6_3">配饰</div>
                         <dl class="L6_4">
                                <dd>皮带</dd>
                                <dd>墨镜</dd>
                                <dd>帽子</dd>
                                <dd>其他饰品</dd>
                        </dl>  

            </div>
            <div class="L7">
            	<div class="L7_1">
                	<div class="L7_1_1">新品</div>
                    <div class="L7_1_2">new</div>
                    <div class="L7_1_3">多相关产品 >></div>
                </div>
                <div class="L7_2"><img src="image/L7_3.gif" /></div>
                <div class="L7_3"><img src="image/L7_3.gif" /></div>
                <div class="L7_4"><img src="image/L7_3.gif" /></div>
                  <div style="clear:both;"></div>
                <div class="L7_5"><img src="image/L7_5.gif" /></div>
            </div>
            <!--中间部分第二块产品分类结束-->
            <div style="clear:both;"></div>
            <div style="height:28px; "></div> 
            <!--中间部分第三块女装开始-->
            <div class="L8">
            	<div class="L7_1">
                	<div class="L7_1_1">女装</div>
                    <div class="L7_1_2">women</div>
                    <div class="L7_1_3">多相关产品 >></div>
                </div>
                <div class="L8_1"><img src="image/L8_1.gif" /></div>
                <div class="L8_2"><img src="image/L8_2.gif" /></div>
            </div>
            <!--中间部分第三块女装结束-->
            <!--中间部分第四块男装开始-->
            <div class="L9"></div>
            <!--中间部分第四块男装结束-->
            <!--中间部分第五块配饰开始-->
            <div class="L10"></div>
            <!--中间部分第五块配饰结束-->
        </div>
      <div style="clear:both;"></div> 
        <!--中间部分结束-->
        <div style="height:28px;"></div>
        <!--底部部分开始-->
        <div class="bottom">
        	        <!--导航栏开始-->
        <div class="navigation">
        	<a href="#"><div class="N1">首页</div></a>
        	<a href="#"><div class="N2">商品中心</div></a>
            <a href="#"><div class="N2">新闻中心</div></a>
            <a href="#"><div class="N2">商城活动</div></a>
            <a href="#"><div class="N2">品牌列表</div></a>
            <a href="#"><div class="N2">帮助中心</div></a>
            <a href="#"><div class="N2">发货通知</div></a>
            <a href="#"><div class="N2">在线留言</div></a>
            <div class="N3">您的购物车里有0件商品</div>
            <div class="N4"><a class="F4" href="#">去结算</a></div>
        </div>
        <div style="clear:both;"></div> 
        <!--导航栏结束-->
        	<div class="a7">长沙源码计算机信息咨询有限公司 版权所有 2010 湘ICP备12182769号 | 联系电话：0731-82259438</div>
        </div>
        <!--底部部分结束-->
    </div>
    <!--外边框结束-->
</body>
</html>
