<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7 charset=utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title> ECMall </title>
<link href="<?php echo $this -> RootUrl(); ?>/adminres/css/admin.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="js/jquery.js" charset="utf-8"></script>
<script type="text/javascript" src="js/ecmall.js" charset="utf-8"></script>
<script type="text/javascript" src="js/admin.js" charset="utf-8"></script>
<style type="text/css">
<!--
body {background: #fcfdff}
-->
</style>
</head>
<body><div id="rightTop">
  <p>修改品牌</p>
  <ul class="subnav">
    <li><a class="btn1" href="<?php echo $this->RootUrl()?>/admin/goodsbrand/index">品牌管理</a></li>
  </ul>
</div>
<div class="info">
  <form method="post" id="add_form" action="<?php echo $this->url(array('action' => 'update')); ?>">
    <table class="infoTable">
      <tr>
          <th></th>
        <td class="paddingT15">品牌信息</td>
      </tr>
      <tr>
        <th class="paddingT15"> 品牌名称:</th>
        <td class="paddingT15 wordSpacing5">
          <input class="infoTableInput2" name="name" type="text" style="width:200px" value="<?php echo $this -> escape($this -> brand -> brand_name); ?>"/>*
        </td>
      </tr>
      <tr>
        <th class="paddingT15"> 品牌描述:</th>
        <td class="paddingT15 wordSpacing5"><textarea class="infoTableInput2" name="description"><?php echo $this -> escape($this -> brand -> description); ?></textarea>*</td>
      </tr>
      <tr>
        <th class="paddingT15"> 排序:</th>
        <td class="paddingT15 wordSpacing5">
          <input class="infoTableInput2" name="orders" type="text" value="<?php echo $this -> escape($this -> brand -> orders); ?>"/>
        </td>
      </tr>
      <tr>
        <th></th>
        <td class="ptb20"><input class="formbtn" type="submit" name="submit" value="修改" />
          <input class="formbtn" type="button" name="back" value="返回" onclick="javascript:history.back();" /></td>
      </tr>
    </table>
  </form>
</div>
<p id="page_footer">&copy;.&copy;。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。&copy;.&copy;</p>
</body>
</html>